const K='trader-reset-v1';let s=JSON.parse(localStorage.getItem(K)||'null')||{trades:[],checks:Array(7).fill(false),locked:false};
const items=[['I know my setup is present','No setup = no trade.'],['Market conditions fit my strategy','Do not force the setup.'],['Entry is clearly defined','Know the trigger.'],['Stop Loss is defined','Risk first.'],['Take Profit is defined','Know the exit.'],['I am within my risk limit','Never increase size after a loss.'],['I am calm and not chasing money','No FOMO or revenge.']];
const save=()=>localStorage.setItem(K,JSON.stringify(s)); const R=()=>s.trades.reduce((a,t)=>a+Number(t.result||0),0);
function score(){if(!s.trades.length)return 100;let bad=s.trades.filter(t=>!t.followed||['FOMO','Revenge'].includes(t.emotion)).length;return Math.max(0,100-bad*12)}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));render()}
function render(){document.getElementById('score').textContent=score();document.getElementById('count').textContent=s.trades.length;document.getElementById('r').textContent=R().toFixed(2)+'R';document.getElementById('breaks').textContent=s.trades.filter(t=>!t.followed).length;document.getElementById('status').textContent=s.locked?'LOCKED':'READY';
document.getElementById('checks').innerHTML=items.map((x,i)=>`<label class="check"><input type="checkbox" data-i="${i}" ${s.checks[i]?'checked':''}><div><b>${x[0]}</b><small>${x[1]}</small></div></label>`).join('');document.querySelectorAll('.check input').forEach(x=>x.onchange=()=>{s.checks[+x.dataset.i]=x.checked;save();render()});
let n=s.checks.filter(Boolean).length,p=document.getElementById('pass');p.disabled=n<7||s.locked;p.textContent=s.locked?'Session locked':n===7?'Checklist passed — trade':`Checklist incomplete (${n}/7)`;
document.getElementById('trades').innerHTML=s.trades.map(t=>`<div class="card"><div class="trade"><b>${t.direction} ${t.instrument}</b><b class="${Number(t.result)>=0?'positive':'negative'}">${Number(t.result)>=0?'+':''}${Number(t.result).toFixed(2)}R</b></div><div class="meta">Setup: ${t.setup||'—'} · Risk: ${t.risk||'—'}% · ${t.emotion}<br>${t.followed?'✅ Plan followed':'⚠️ Plan not followed'}</div></div>`).join('');
document.getElementById('review').innerHTML=`<h3>Process score: ${score()}/100</h3><p>${s.trades.length} trade(s) · ${R().toFixed(2)}R · ${s.trades.filter(t=>!t.followed).length} rule break(s).</p><p>${s.trades.length?R()<0?'A losing day can still be a successful process day.':'Profit is a result; repeatable execution is the target.':'No trades logged. Waiting is part of trading.'}</p><p class="meta">V1 uses local rule-based review. Real AI coaching can be connected in V2.</p>`}
document.getElementById('pass').onclick=()=>show('journal');document.getElementById('form').onsubmit=e=>{e.preventDefault();if(s.locked)return;let f=new FormData(e.target),t=Object.fromEntries(f);t.followed=f.get('followed')==='on';s.trades.unshift(t);s.checks=Array(7).fill(false);if(s.trades.length>=3&&R()<=-2)s.locked=true;save();e.target.reset();render()};document.getElementById('reset').onclick=()=>{if(confirm('Reset today?')){s={trades:[],checks:Array(7).fill(false),locked:false};save();show('home')}};render();